<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>TewiMP</Product>
		<Title>TewiMP</Title>
		<Version>0.0.7.1</Version>
		<AssemblyVersion>0.0.7.1</AssemblyVersion>
		<FileVersion>0.0.7.1</FileVersion>
		<VersionPrefix>0.0.7.1</VersionPrefix>
		<VersionSuffix>beta</VersionSuffix>
		<Company>TewiStudio</Company>
		<Authors>TewiStudio</Authors>
		<Copyright>© 2026 TewiStudio. All Rights Reserved.</Copyright>
		<PackageProjectUrl>https://github.com/TewiStudio/TewiMP</PackageProjectUrl>
	</PropertyGroup>
	<PropertyGroup>
		<RootNamespace>TewiMP</RootNamespace>
		<AssemblyName>TewiMP</AssemblyName>
		<OutputType>WinExe</OutputType>
		<WindowsSdkPackageVersion>10.0.22621.56</WindowsSdkPackageVersion>
		<TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<NeutralLanguage>zh-CN</NeutralLanguage>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<PublishTrimmed>False</PublishTrimmed>
		<PublishAot>False</PublishAot>
		<ApplicationIcon>Assets\Images\Icons\icon.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ImplicitUsings>disable</ImplicitUsings>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <DebugType>embedded</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <DebugType>embedded</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
	  <DebugType>embedded</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <DebugType>embedded</DebugType>
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <DebugType>embedded</DebugType>
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
	  <DebugType>embedded</DebugType>
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Background.zip" />
		<None Remove="UI\Controls\DownloadCard.xaml" />
		<None Remove="UI\Controls\ImageEx.xaml" />
		<None Remove="UI\Controls\ItemListViewArtist.xaml" />
		<None Remove="UI\Controls\ItemListViewPlayList.xaml" />
		<None Remove="UI\Controls\ItemListViewSearch.xaml" />
		<None Remove="UI\Controls\KeyControl.xaml" />
		<None Remove="UI\Controls\LoadingTip.xaml" />
		<None Remove="UI\Controls\LyricItem.xaml" />
		<None Remove="UI\Controls\MainMusicDataItem.xaml" />
		<None Remove="UI\Controls\ManageLocalMusicFolderControl.xaml" />
		<None Remove="UI\Controls\MediaPlayStateViewer.xaml" />
		<None Remove="UI\Controls\MusicDataFlyout.xaml" />
		<None Remove="UI\Controls\MusicDataItem.xaml" />
		<None Remove="UI\Controls\NotifyItem.xaml" />
		<None Remove="UI\Controls\PlayListCard.xaml" />
		<None Remove="UI\Controls\ScrollFootButton.xaml" />
		<None Remove="UI\Controls\ScrollViewerSearchControl.xaml" />
		<None Remove="UI\Controls\SongHistoryCard.xaml" />
		<None Remove="UI\Controls\SongHistoryInfo.xaml" />
		<None Remove="UI\Controls\ImageEx.xaml" />
		<None Remove="DesktopLyricWindow.xaml" />
		<None Remove="UI\Pages\BrowsePage.xaml" />
		<None Remove="UI\Pages\DialogPages\AddFilesToMusicListDataPage.xaml" />
		<None Remove="UI\Pages\DialogPages\AddPlayListPage.xaml" />
		<None Remove="UI\Pages\DialogPages\AudioInfoPage.xaml" />
		<None Remove="UI\Pages\DialogPages\EditPlayListPage.xaml" />
		<None Remove="UI\Pages\DialogPages\EqualizerPage.xaml" />
		<None Remove="UI\Pages\DialogPages\HotKeyEditor.xaml" />
		<None Remove="UI\Pages\DialogPages\HotKeyPage.xaml" />
		<None Remove="UI\Pages\DialogPages\InsertPlayListPage.xaml" />
		<None Remove="UI\Pages\DialogPages\TimeEventPage.xaml" />
		<None Remove="UI\Pages\DownloadPage.xaml" />
		<None Remove="UI\Pages\EmptyPage.xaml" />
		<None Remove="UI\Pages\HistoryPage.xaml" />
		<None Remove="UI\Pages\ListViewPages\ItemListViewAlbum.xaml" />
		<None Remove="UI\Pages\ListViewPages\PlayListPage.xaml" />
		<None Remove="UI\Pages\LocalAudioPage.xaml" />
		<None Remove="UI\Pages\MusicPage.xaml" />
		<None Remove="UI\Pages\PlayListPage.xaml" />
		<None Remove="UI\Pages\SearchPage.xaml" />
		<None Remove="UI\Pages\SettingEqPage.xaml" />
		<None Remove="UI\Pages\SettingHotKeyPage.xaml" />
		<None Remove="UI\Pages\SettingPage.xaml" />
		<None Remove="UI\Windows\ImageViewerWindow.xaml" />
		<None Remove="UI\Windows\MediaPlayerWindow.xaml" />
		<None Remove="UI\Windows\NotifyIconWindow.xaml" />
		<None Remove="UI\Windows\TaskBarInfoWindow.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CoelWu.Music.SDK" Version="1.0.7" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.OpacityMaskView" Version="0.1.250826-build.2212" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.TokenView" Version="0.1.250828-build.2223" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.TransitionHelper" Version="0.1.251217-build.2433" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.HeaderedControls" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.RadialGauge" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.RangeSelector" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.ColorPicker" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="DevWinUI" Version="10.0.0" />
		<PackageReference Include="Downloader" Version="5.9.4" />
		<PackageReference Include="ksemenenko.ColorThief" Version="1.1.1.4" />
		<PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.298">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
		<PackageReference Include="NAudio" Version="2.3.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="PInvoke.BCrypt" Version="0.7.124" />
		<PackageReference Include="PInvoke.NCrypt" Version="0.7.124" />
		<PackageReference Include="PInvoke.User32" Version="0.7.124" />
		<PackageReference Include="PInvoke.Windows.Core" Version="0.7.124" />
		<PackageReference Include="SoundTouch.Net.NAudioSupport" Version="2.3.2" />
		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="System.Runtime.InteropServices.WindowsRuntime" Version="4.3.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.9" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="5.0.5" />
		<PackageReference Include="WinUIEx" Version="2.9.1" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<None Update="ffmpeg.exe">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Assets\Images\Icons\icon.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="LICENSE">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Plugins\FFmpegPathSelector.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Plugins\NeteaseMusicSource.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Page Update="DesktopLyricWindow.xaml">
			<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
			<SubType>Designer</SubType>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<Target Name="RemovingLanuageFolders" AfterTargets="Build">
		<ItemGroup>
			<RemovingFiles Include="$(OutDir)*\*.mui" Exclude="$(OutDir)zh-CN\*.mui" />
			<RemovingFolders Include="@(RemovingFiles->'%(RootDir)%(Directory)')" />
		</ItemGroup>
		<RemoveDir Directories="@(RemovingFolders)" />
	</Target>
</Project>
